<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>GunGameBotAI</AssemblyName>
    <RootNamespace>GunGameBotAI</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.375" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GunGameAPI\GunGameAPI.csproj" />
  </ItemGroup>

</Project>
